version: '3.5'

services:
  app:
    build: .
    environment:
      - http_proxy=http://tinyproxy:8888
      - https_proxy=http://tinyproxy:8888
    restart: unless-stopped
    networks:
      - reverse_proxy
      - forward_proxy

  reverseproxy:
    image: nginx:1.15-alpine
    ports:
      - 80:80
    volumes:
      - ./tools/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    restart: unless-stopped
    networks:
     - reverse_proxy
     - internet

  tinyproxy:
    build: ./tools/tinyproxy/
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - forward_proxy
      - internet

networks:
  reverse_proxy:
    internal: true
  forward_proxy:
    internal: true
  internet:


# vim: set tabstop=2:
