version: '3.5'

services:
  app:
    build: .
    restart: unless-stopped
    networks:
      - reverse_proxy

  reverseproxy:
    image: nginx:1.15-alpine
    ports:
      - 80:80
    volumes:
      - ./tools/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    restart: unless-stopped
    networks:
     - reverse_proxy
     - internet

networks:
  reverse_proxy:
    internal: true
  internet: